### ISSUE TITLE
GBIF occ_download_get

### ISSUE THREAD

**Issue by eb-bruns** [MortonArb-CollectionsValue/OccurrencePoints#3]
For some reason I'm getting a "Error in curl::curl_fetch_disk(x$url$url, x$disk, handle = x$url$handle)" error when I try to run the occ_download_get() function in the 2-0_get_raw_occurrence_points.R script (line 195-196). 
@calpoppy if you could run the script from the beginning through the GBIF part (end at line 288), that would be helpful. I *think* the error has to do with my computer setup and not the function itself, but we will see!
I am working through the rest of the script and will hopefully be finished tomorrow!

**Comment by calpoppy** [comment]
FYI, I am going through this. I am currently on line ~200. Takes a bit to download the data, but I should be at your error line soon.

**Comment by calpoppy** [comment]
I get an error at the same spot. The download starts and then fails with the following message:
"Download file size: 646.2 MB
Error in occ_download_get(key = download_key[1], path = file.path(main_dir,  : 
  res$response_headers$`content-type` == "application/octet-stream; qs=0.5" is not TRUE"

**Comment by eb-bruns** [comment]
Hm... ok, thanks for trying! Interesting I don't get quite the same error. I know in the past I've had a problem with the occ_download_get() function and had to do a work-around. I can look into that, unless you're on a roll right now and want to give it a try. 
I'm working through the 2-1_compile_exsitu_data.R script now and will likely open another issue for a few things in that script.

**Comment by calpoppy** [comment]
Just tried again and got the same error.
I may attempt to download onto my computer rather than the GoogleDrive, and see if that works.

**Comment by calpoppy** [comment]
OK. I got the same error message when d/l to my computer...but I still have a zip file downloaded. I noticed that I am able to move on to the next few lines and bring in that data. That is weird. So, the .zip is there, and on Mac shows that it is not complete (d/l "wheel" is half full), but then the size is correct (646.2 MB) and the file opens.
![Screen Shot 2020-07-22 at 1 10 19 PM](https://user-images.githubusercontent.com/3300833/88223699-b7061080-cc1c-11ea-9bcc-225e3e52d6db.png)

**Comment by eb-bruns** [comment]
Strange.. is there a way we can fix the script so it runs through, or should we just add a comment explaining what to do manually before moving on?

**Comment by calpoppy** [comment]
I do not know how to answer. I am currently on the SERNEC/SEINet/etc. data and am running through. I would have to see if the error breaks the entire script or it will run with that error there. But also I am not sure if you would receive the same error, and maybe it would break differently for you.

**Comment by calpoppy** [comment]
Let me run through this and then I will just attempt to run the entire script without intervention and see if it goes through.

**Comment by eb-bruns** [comment]
Ok sounds good. Note that I added a section for downloading the FIA data directly from the URLs (so it doesn't have to be done manually), but it takes a long time... so you probably want to skip that part since I did it yesterday and its in the shared drive. I guess maybe we could split that part into a different script that goes before? Not sure. Ideally you would just need to run the script once for a project and then it wouldn't be a problem

**Comment by calpoppy** [comment]
OK. I have run the script and it goes past that point. If there is an error, it is at least still letting me download and open the zip, and run the rest of the script. I am running through the rest of the script and can push any changes later tonight.
I think that this specific issue is closed, at least on my end.
