### ISSUE TITLE
3-1_geo_data_work.R

### ISSUE THREAD

**Issue by eb-bruns** [MortonArb-CollectionsValue/OccurrencePoints#5]
@calpoppy I'm working through script 3-1_geo_data_work.R (we can rename/reorganize later as desired). It will look at "known_distribution" data and use it to crop occurrence point data.

Line 106 looks incomplete? Not sure exactly what it was supposed to be. 

Thanks!

**Comment by calpoppy** [comment]
OK. Through line 106 only needs to be run once, and it creates files. It doesn't need to be rerun again each time. That section could go into a different script. However, that small portion right at line 106 is incomplete, and was commented out as I was attempting something else. We can remove for now if we want.
I'm trying to go through the rest of the script right now.

**Comment by calpoppy** [comment]
OK. I have moved some of the code from 3-1 to a new script, 1-1_prepare_gis_data.R. This new script is simply to prepare all of the GIS data and store in an .RData file to retrieve in later scripts (such as 3-1).
The current iteration of 3-1 should work. I have changed the file paths to work. I have not reformatted, though. The lines still break after 80, and I didn't go through that yet.
Please close this comment if we addressed the situation above.
