### ISSUE TITLE
5-0_plot_occurrences

### ISSUE THREAD

**Issue by calpoppy** [MortonArb-CollectionsValue/OccurrencePoints#7]
I noticed that on the couple maps I examined (Q. lobata and Q. kelloggii) the png maps bascially show the native range and the html show those that appear in collections. There are no California plants in either html file.
Do you know why? 
This may make sense when I take more time to look. I didn't immediately see it.

**Comment by eb-bruns** [comment]
I think this will be resolved by fixing the loop, as we discussed on the phone. I'll let you close this issue though when you see its fixed.
